### ISSUE TITLE
Cannot parse resign

### ISSUE THREAD

**Issue by Dorus** [fsparv/LeelaWatcher#14]
see https://github.com/gcp/leela-zero/issues/306

Resignation was recently turned on and LeelaWatcher crashes on it.

**Comment by FelixBrendel** [comment]
Are you using the latest release? 
![image](https://user-images.githubusercontent.com/5005975/33784296-a1d73dbe-dc60-11e7-9d76-e06942ad8032.png)
The latest version of LeelaWatcher should parse the resignation.

**Comment by fsparv** [comment]
Duplicate of #13
