### ISSUE TITLE
Is a quick update possible? Only a simple regex change required

### ISSUE THREAD

**Issue by FFLaguna** [fsparv/LeelaWatcher#23]
Can we get an update for the most recent Leela releases? I understand it's just a simple Regex change (there is already a pull for this). I tried changing the jar manually on my end, but failed completely. Can @fsparv make this quick change if he has any spare time? Thanks!

**Comment by fsparv** [comment]
I've been pretty busy, sorry. I do want to get to this, but I do have to find time to review it. In the future, it's sufficient to comment on the existing issue. I get a notification either way. Creating a separate issue just clutters things.
