### ISSUE TITLE
simplify SGFFileFilter

### ISSUE THREAD

**Issue by barrybecker4** [fsparv/LeelaWatcher#25]
9 lines can be replaced with 1 using toUppercase instead of all the permutations. I'll make a PR.

**Comment by fsparv** [comment]
lol, now you've gone and found some of my 2001 code :)... I'm sure there's lots of silliness like that to be cleaned up. I had just learned java when I wrote most of this code. That's simple enough I can merge it at a glance...

**Comment by barrybecker4** [comment]
Closing this since my PR was merged.
