### ISSUE TITLE
Games shown by LeelaWatcher aren't correct!

### ISSUE THREAD

**Issue by grolich** [fsparv/LeelaWatcher#9]
I found a surprisingly commonly occurring problem when using LeelaWatcher.
Many moves that the watcher correctly read from autogtp/Leela zero (and shown it read them) are completely skipped in the SGF, creating a completely false representation of the game.

An example:

**Here's the SGF Leela was showing and writing during play**:
http://eidogo.com/#1cWKYlvGj

[Suspicious-game-2017-11-27T20_58_38.724Z.sgf.zip](https://github.com/fsparv/LeelaWatcher/files/1508152/Suspicious-game-2017-11-27T20_58_38.724Z.sgf.zip)

**Here's the program's output**:
[Suspicious game.zip](https://github.com/fsparv/LeelaWatcher/files/1508146/Suspicious.game.zip)

Initially I thought it was a problem with legal/Illegal moves, as near the end of the game MANY illegal moves were skipped; However, going over the game from move 1, the first omission, on move 326 in the program's output, shows a completely legal move (actually 4 in a row) not being added to the SGF. 

Looking ahead, it seems it happened dozens of times during the game, often with an odd number of moves, so eventually a black move was placed as a white move etc. 
This turned more of the moves later in the game to illegal ones.

Stones that were captured by white in the actual moves Leela was giving were connected by black in this
sgf/LeelaWatcher view, and later Leela tried to play in the open spaces created where the captured stones were, which was, of course, illegal, etc.

The problem doesn't seem to be a rare one and I have noticed it in several games.

**Comment by grolich** [comment]
To make things easier for anyone wanting to check the output - 
Some of the moves in the output file which weren't played in the SGF-

326-329 (all ranges are inclusive with respect to the last element)
333, 340, 343, 349,350,351, 353, 356,357... And many more. Including end of game - 410-417  - last move in the output before the double passes. By that point, too many moves actually played by Leela are illegal in the target SGF/ Watcher view anyway.

**Comment by nsoft** [comment]
Thanks for the report, this may relate to issue #4. This seems to raise the question of whether Leela is playing by the same rules... The very first thing that should be done here is to raise an error if the watcher thinks a move was illegal, and print that out. Secondarily I need to verify exactly what moves Leela is being allowed to play and make sure my rules implementation matches and allows the same moves.

**Comment by nsoft** [comment]
Hmm looking at the game in detail this seems even more odd than that.

**Comment by nsoft** [comment]
Ah this may mean that the stones that should have been captured were not captured and thus the next 4 were considered illegal, a potential symptom of #4
